
// Export all assets from this file
export { default as visaLogo } from './Visa Logo.svg';
export { default as aspireLogo } from './Aspire_Logo.svg';
export { default as aspireLogoWhite } from './Aspire_Logo-1.svg';
export { default as nextArrow } from './next.svg';
export { default as nextArrow1 } from './next-1.svg';
export { default as nextArrow2 } from './next-2.svg';
export { default as nextArrow3 } from './next-3.svg';
export { default as addIcon } from './add.svg';
export { default as eyeIcon } from './remove_red_eye-24px.svg';
export { default as eyeIcon1 } from './remove_red_eye-24px-1.svg';
export { default as natureIcon } from './nature (1).svg';
export { default as natureIcon1 } from './nature (1)-1.svg';
export { default as deactivateCardIcon } from './Deactivate card.svg';
export { default as fileStorageIcon } from './file-storage.svg';
export { default as fileStorageIcon1 } from './file-storage-1.svg';
export { default as creditIcon } from './Credit.svg';
export { default as flightsIcon } from './flights.svg';
export { default as megaphoneIcon } from './megaphone.svg';
export { default as payIcon } from './pay.svg';
export { default as cardIcon } from './Card.svg';
export { default as userIcon } from './user.svg';
export { default as gPayIcon } from './GPay.svg';
export { default as exchangeIcon } from './77cfcfe5525d392a91457d5e35b0352c.svg';
export { default as replaceCardIcon } from './Replace card.svg';
export { default as accountIcon } from './Account.svg';
export { default as freezeCardIcon } from './Freeze card.svg';
export { default as groupIcon } from './Group 11889.svg';
export { default as groupIcon1 } from './Group 11889-1.svg';
export { default as pickupCarIcon } from './pickup-car.svg';
export { default as spendLimitIcon } from './Set spend limit.svg';
export { default as downArrowIcon } from './down-arrow.svg';
export { default as downArrowIcon1 } from './down-arrow-1.svg';
export { default as boxIcon } from './box.svg';
export { default as businessFinanceIcon } from './business-and-finance.svg';
export { default as businessFinanceIcon1 } from './business-and-finance-1.svg';
export { default as businessFinanceIcon2 } from './business-and-finance-2.svg';
export { default as businessFinanceIcon3 } from './business-and-finance-3.svg';
export { default as homeIcon } from './Home.svg';
export { default as paymentsIcon } from './Payments.svg';
